### PR TITLE
SwiftLint CI Changes

### PR DESCRIPTION
**Pull request by Sherlouk**
Replaces #1067 because I suck at rebasing 🥉

### CODE REVIEW

**Comment by jessesquires** [comment]
I think it would be ideal to keep SwiftLint updated, because travis can be slow to update.

What if we do this?

- We check if swiftlint (any version) is installed
    - if correct one is not installed, trigger a warning but run SwiftLint anyway
    - if correct is installed, run it
- If no version is installed at all, `exit 1`

**Comment by jessesquires** [comment]
turns out my other projects had the same problem. lol 😳 

my solution:
https://github.com/jessesquires/JSQDataSourcesKit/pull/109

**Comment by Sherlouk** [comment]
@jessesquires pull your changes over they look perfect!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
pushed updates to this PR 😄

**Comment by jessesquires** [comment]
@Sherlouk  @rnystrom 

Oh -- just realized this is not merging into master. we should update

**Comment by jessesquires** [comment]
actually --- i'll just make all these changes together at #1068

**Pull request closed without merging**
