### PR TITLE
Adapts to dark mode for iOS example project.

### PR DESCRIPTION
**Pull request by dirtmelon**
### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by lorixx** [comment]
Love it! Thank you so much @dirtmelon !

**Comment by joetam** [comment]
would it be possible to introduce a `UIColor` extension that uses the #available checks within it and switch between the new apis like `labelColor` and the hardcoded colors? That would help to keep the callsites a little bit cleaner and allow the examples to focus on the critical/relevant integration points

**Review by lorixx — CHANGES_REQUESTED** [review]
Good suggestion by @joetam ! Can you add an UIColor extension to keep things cleaner? Thanks!

**Comment by dirtmelon** [comment]
Done. @joetam @lorixx Thanks for reviewing.

**Pull request closed without merging**
