### PR TITLE
RFC: Diff in the background

### PR DESCRIPTION
**Pull request by rnystrom**
Experimenting with a new change. We have observed instances of very large (3k+) lists stalling, even on modern devices. This is especially noticeable if the models being diffed are:

- Immutable
- `performUpdates:` often and models are alloc/init'd each time
- The `isEqualToDiffableObject:` is sort of expensive (many `-[NSString isEqualToString:]` across thousands of models or something)

Instead of just rolling this out, I plan on experimenting with results and seeing how much of a performance and stability boost we gain w/ this. Things to measure:

- Scroll performance
- CPU stalls
- WatchDog kills on older devices

### CODE REVIEW

**Comment by rnystrom** [comment]
Can force test suite to run by changing:

```objc
if (IGListExperimentEnabled(experiments, IGListExperimentBackgroundDiffing)) {
```
to
```objc
if (YES || IGListExperimentEnabled(experiments, IGListExperimentBackgroundDiffing)) {
```
Tests are all ✅ w/ that hack.

**Comment by rnystrom** [comment]
Importing for eyeballs. Omitting changelog for now since its an experimental change.

**Comment by rnystrom** [comment]
@jessesquires if you get a minute want to run over this one? It's PSC week and nobody is reviewing internally 😆

**Comment by amonshiz** [comment]
hey, now that i'm on PTO i've got time. ;)

**Comment by jessesquires** [comment]
@rnystrom @amonshiz

**Comment by jessesquires** [comment]
Seems legit to me 🤷‍♂️

**Comment by weyert** [comment]
Did you experience any improvements with this new approach you are suggesting here?

**Comment by rnystrom** [comment]
@weyert will report back w/ findings 😉

**Pull request closed without merging**
