### PR TITLE
IGListDiffKit should support APPLICATION_EXTENSION_API_ONLY

### PR DESCRIPTION
**Pull request by pm-dev**
## Changes in this pull request

Issue fixed: #1421

This PR checks the box that indicates the framework is safe to be used in App Extensions
Screen Shot 2020-02-08 at 3 27 47 PM

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
@pm-dev rebasing against `master` will get the CI tests passing again. The fix for failure you're seeing here was finally merged 12 hours ago: https://github.com/Instagram/IGListKit/pull/1425

**Comment by pm-dev** [comment]
@aaronbrethorst looks like the Pod Lint step of CI is still failing.
`bundle exec pod lib lint --allow-warnings "--include-podspecs=*.podspec"`

Results in a failure:
`- ERROR | [OSX] unknown: Encountered an unknown error (The platform of the target `App` (macOS 10.11) is not compatible with `IGListSwiftKit (4.1.0)`, which does not support `macOS`.) during validation.`

@koenpunt Looks like you added IGListSwiftKit. Do you mind taking a look?

**Comment by 3a4oT** [comment]
Can we expect a minor release anytime soon?

**Comment by 3a4oT** [comment]
ping @lorixx ;

**Comment by lorixx** [comment]
Thanks @pm-dev and @3a4oT ! I have fixed the CI Travis build+lint errors, pls rebase and re-trigger the CI build, once it's green I am happy to merge, thanks!

**Comment by pm-dev** [comment]
Thanks @lorixx. Checks are passing

**Comment by lorixx** [comment]
Awesome! Merging now

**Pull request closed without merging**
