### PR TITLE
Add new iOS 11 api adjustedContentInset support

### PR DESCRIPTION
**Pull request by yiplee**
adopt adjustedContentInset instead of contentInset on iOS 11

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
Awesome! Would love a change log entry and even a unit test for this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yiplee** [comment]
Change log entry and unit test added :)

**Comment by yiplee** [comment]
screen shot 2017-11-22 at 01 37 48

Yes, the new files have been included by pod.

**Comment by rnystrom** [comment]
@yiplee are the examples building for you?

**Comment by yiplee** [comment]
@rnystrom  I agree with you. But the bug will remain exist if people forget to replace ```containerInset``` by ```adjustedContainerInset``` in their codes.  And in my opinion, when people call context's ```containerInset```, they expect context to return the real content inset applied to scroll view.

**Comment by rnystrom** [comment]
@yiplee though even more about this, I think the only way to go is with a separate API. I found a few places that will break in Instagram if we make this change, so that’s a blocker.

Would you be ok making this a separate API? Thanks!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yiplee** [comment]
@rnystrom It's OK. I will update the PR right now. 😄

**Pull request closed without merging**
