### PR TITLE
Fix incorrect class in variable definitions

### PR DESCRIPTION
**Pull request by antons**
## Changes in this pull request

Fix incorrect class in variable definitions in IGListIndexPathResult. No change in functionality, nothing to test.

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
Actually the reason we use a set is to make the object lookups `O(1)`, if we change these to arrays we'll end up with an `O(n^2)` method.

**Comment by antons** [comment]
@rnystrom In that case it’s currently `O(n^2)`, because these three variables are mutable arrays, not sets.

**Comment by rnystrom** [comment]
@antons good eye! Looks like this got lost in refactoring. Want to fix it so we're operating on sets w/in this algorithm?

**Comment by antons** [comment]
@rnystrom Initially I thought it was a remnant of an old API, where ivars were sets, so I corrected the definition. I see two options to fix the bug:

```objc
NSMutableSet<NSIndexPath *> *deletes = [NSMutableSet setWithArray:self.deletes];
```
If the order of elements is important, ordered set could be a better option:
```objc
NSMutableOrderedSet<NSIndexPath *> *deletes = [NSMutableOrderedSet orderedSetWithArray:self.deletes];
```

**Comment by rnystrom** [comment]
@antons let's go w/ the first one, order isn't important at all. The only reason we ended up w/ `NSArray` for the result public API was that its (a little) easier to work w/ for consumers.

Thanks for digging on this!

**Comment by antons** [comment]
@rnystrom My pleasure, and thank you for open sourcing this! I’ll submit a new pull request for the bug fix.

**Pull request closed without merging**
