### PR TITLE
macOS example app

### PR DESCRIPTION
**Pull request by insidegui**
Related issue: #333 

I've made a very simple macOS example app. It's just a list of names which can be searched, shuffled or deleted.

I think this is a good starting point for anyone who wants to use this on macOS projects :)

iglistkitmac

### CODE REVIEW

**Comment by jessesquires** [comment]
@insidegui that gif looks awesome! 🎉

**Comment by rnystrom** [comment]
Omg this is great!

**Comment by antons** [comment]
We’re using IGListKit with NSTableView, and I must mention an important point about moves. While UITableView expects to be told where each row was and where it was and where it is now, NSTableView requires moves to be reported incrementally. If moves are reported as they are now, multiple moves will often result in an inconsistent internal state and crashes. 

As far as I can see, NSCollectionView uses the newer behavior found in UITableView and UICollectionView.

I’ve added an option for reporting incremental moves to our internal copy of IGListDiff. Besides NSTableView, it’s useful for replaying changes on collections. Let me know if you’d like me to submit a pull request with it.

**Comment by antons** [comment]
To give a concrete example, try replacing implementation of UsersViewController.shuffle() with:

```swift
var usersModified = users
let second = users[1]
usersModified.remove(at: 1)
usersModified.insert(second, at: 0)
users = usersModified
```

This produces a diff with:
```
<IGListIndexSetResult 0x600000073300; 0 inserts; 0 deletes; 0 updates; 2 moves>
▿ 2 elements
  - 0 : <IGListMoveIndex 0x6000000268c0; from: 1; to: 0;>
  - 1 : <IGListMoveIndex 0x60000002d720; from: 0; to: 1;>
```

Before: 

```
▿ 201 elements
  - 0 : "Aaron"
  - 1 : "Abigail"
…
```

After:
```
▿ 201 elements
  - 0 : "Abigail"
  - 1 : "Aaron"
…
```

Since NSTableView applies moves incrementally, it moves row at index 1 to 0, then moves row at index 0 (the row it just moved from index 1 in previous step) to 1. As a result, there’s no visible change, and the visible state does not match the data source.

**Comment by insidegui** [comment]
@antons I didn't know that, thanks for reporting. I think a pull request would be really helpful, but let's see what @jessesquires and @rnystrom think about it :)

**Comment by jessesquires** [comment]
@antons Thanks! 😄 I would definitely like to see a PR if you have the time 👍

**Comment by jessesquires** [comment]
@antons Let's also open a new issue for this 😊

**Pull request closed without merging**
