### PR TITLE
Remove IGListGridCollectionViewLayout

### PR DESCRIPTION
**Pull request by rnystrom**
## Changes in this pull request

Follow from #450, this layout has been replaced. You served us well!

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.

### CODE REVIEW

**Comment by Sherlouk** [comment]
😢 Emotional times!

Other than a name change, is the new layout essentially like for like?

**Comment by zhubofei** [comment]
@rnystrom we need to remove/modify the examples that use grid layout as well.

**Comment by rnystrom** [comment]
Demo isn't totally the same as previous layout, but just about there. We don't have `IBInspectable` properties yet, but we can add those next.

simulator screen shot feb 10 2017 8 23 35 pm

**Comment by zhubofei** [comment]
👍👍👍

**Pull request closed without merging**
