### PR TITLE
IGListSingleSectionControllerDelegate: add deselect delegate method

### PR DESCRIPTION
**Pull request by darrenclark**
## Changes in this pull request

Added `-didDeselectSectionController:withObject:` to `IGListSingleSectionControllerDelegate`.

Not sure if it makes sense to make it non-optional in 4.0.0 or not (#909) - I can add the [same note](https://github.com/Instagram/IGListKit/blob/0f04a073194033fbfc6f1d916fad83838042a7c0/Source/IGListBindingSectionControllerSelectionDelegate.h#L40) to the docs if it is

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by weyert** [comment]
Thank you!

**Comment by rnystrom** [comment]
I’m out of town for the week, looking forward to reviewing this when I’m back. Very cool!

By design we want to completely avoid using `@optional` entirely. Lets put a disclaimer about it being removed in 4.0.0.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
Maybe it's an idea to already have a default implementation for it for this PR? To avoid more work when working on 4.0.0?

**Comment by rnystrom** [comment]
@weyert not sure what you mean? We want this to be `@optional` until 4.0 when we relive it. Otherwise this would be a _Breaking Change_ which violates our semantic versioning (no BCs until major versions).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by darrenclark** [comment]
Cool, sounds good

**Comment by weyert** [comment]
You are totally right, @rnystrom. Tried to be efficient 🤓

**Comment by rnystrom** [comment]
@darrenclark sorry for the delay! If you wouldn't mind hitting up those conflicts I can land ASAP.

**Comment by darrenclark** [comment]
Thanks!

**Pull request closed without merging**
