### PR TITLE
Regen docs for 3.0

### PR DESCRIPTION
**Pull request by rnystrom**
~~Land after #661, #730 and D5031184~~

Rebuild the docs from script. Couple notes:

- Went from 100% to 99%, does that matter? Script output says
  - > 99% documentation coverage with 2 undocumented symbols
  - Looks like `NS_SWIFT_NAME` throws documentation for a loop on `IGListDiffOption` and `IGListExperiment`
- Swift names are different, will that be a problem?

Part of #707

#trivial

### CODE REVIEW

**Comment by jessesquires** [comment]
@rnystrom -- do those 2 symbols still show up in the generated docs and the % is just wrong? or does jazzy actually not generate docs?

**Comment by rnystrom** [comment]
Docs are there, I think jazzy counts them as 2x since we have the Swift rename annotation.

**Comment by jessesquires** [comment]
found a few minor pods issues and re-podded. otherwise all looks good to land!

**Comment by jessesquires** [comment]
going to proof-read later and import

**Pull request closed without merging**
