### PR TITLE
Convert NSUInteger to NSInteger

### PR DESCRIPTION
**Pull request by zhubofei**
## Changes in this pull request
#431

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.

No breaking changes that I am aware of.

### CODE REVIEW

**Comment by zhubofei** [comment]
Nothing is breaking. IMHO, we can push this one in 2.2.0.

**Comment by jessesquires** [comment]
Wait -- doesn't this change the Swift APIs when this is imported?

cc @rnystrom @zhubofei

**Comment by rnystrom** [comment]
@jessesquires should all be internal changes

**Comment by zhubofei** [comment]
@jessesquires There's no public API changes in this PR.

**Comment by jessesquires** [comment]
ah right 👍

**Pull request closed without merging**
