### PR TITLE
Remove `@param` alignment from header docs #trivial

### LINKED ISSUE #655: Remove all @param alignment style in header docs
Keeping param descriptions aligned (adding whitespace) is too difficult to maintain and we end up in weird states [like this](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L89-L91) over time. We need to do a pass over all headers and clean this up.

### PR DESCRIPTION
**Pull request by BasThomas**
## Changes in this pull request

Issue fixed: #655

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

I've also addressed a few cases where there was no empty line between the `@param`s and `@return`.

### CODE REVIEW

**Comment by BasThomas** [comment]
😂 awesome @jessesquires

**Comment by rnystrom** [comment]
@BasThomas omg hero 🙌

**Comment by BasThomas** [comment]
☺️

**Comment by heshamsalman** [comment]
This is awesome :+1:

**Pull request closed without merging**
