### PR TITLE
Swap NSUInteger to NSInteger Public API

### PR DESCRIPTION
**Pull request by surayashivji**
## Changes in this pull request
Swapped NSUInteger to NSInteger in public headers. Fixed a test in IGListSectionMapTests.m to pass with NSInteger. For issue #200! 

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
Looks like a race condition w/ #206 😂 

I can take this one since it was first in, but we should probably revert all the `docs/` and podfile changes. We're tracking to update that in #181 (right before 2.0.0 cut).

**Comment by surayashivji** [comment]
Cleaned up the branch!

**Comment by rnystrom** [comment]
Gonna let CI ✅ then we're g2g!

**Comment by jessesquires** [comment]
LGTM. thanks @surayashivji ! 🎉

**Comment by surayashivji** [comment]
Updated the Changelog!

**Comment by rnystrom** [comment]
@surayashivji last thing w/ the changelog, can you use the same format as items in **Enhancements**? Name (PR#). I believe the commit hash will change due to how we sync PRs.

**Comment by surayashivji** [comment]
Updated CHANGELOG.md-- thank you!

**Comment by jessesquires** [comment]
Thanks @surayashivji ! 💯

**Pull request closed without merging**
