### PR TITLE
Reorganize code into demo groups

### PR DESCRIPTION
**Pull request by Krishna**
## Changes in this pull request

Issue fixed: https://github.com/Instagram/IGListKit/issues/712

Reorganized the source code of the iOS Demo projects. The source code for each demo is now in individual groups/folders. Shared code is under a Shared folder:

```
- Tail Loading
   // all files for tail loading
- Search Auto Complete
   // all files search
- ... other demo groups...
- Shared
   // all shared files
```
I ran the tests for the demos, and there are two failures in the SearchViewControllerUITests. These tests are failing in the main branch also, so my changes are not causing these failures.

### Checklist

- [x]  Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Krishna** [comment]
Hi,

This PR has been open for a while now. Was just wondering if there is anything I need to do on my end to help get it merged in?

**Comment by rnystrom** [comment]
Hey @Krishna, no sorry our internal import tools converted all of your `git move`s into delete+adds which would wipe history. I'm trying to sort it all out, sorry for the hold up!

**Comment by Krishna** [comment]
Hi @rnystrom - thanks for letting me know.

**Comment by rnystrom** [comment]
Closing b/c I fell behind and things have changed a ton. Idk if this is a huge issue.

**Pull request closed without merging**
