### PR TITLE
fixed broken example project

### PR DESCRIPTION
**Pull request by heumn**
## Changes in this pull request

- The recent addition of `IGListCollectionViewLayoutInternal.h` in a80245a696d0fe96777f796eef92cef5942aed7c broke the example project. This PR fixes this.
- Name sorted the internal files

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] Why didnt Travis catch this? 🤔 
- [X] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [X] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
Ah nice, thank you @heumn! Can you run the `./Examples/pod_setup.sh` as well? It looks like the tvOS builds are failing, I think that should fix it.

**Comment by rnystrom** [comment]
> Why didnt Travis catch this?

That diff was landed internally, we use our own CI with [buck](https://github.com/facebook/buck) and don't build these examples.

**Comment by heumn** [comment]
>> Why didnt Travis catch this?
> That diff was landed internally, we use our own CI with buck and don't build these examples.

Got it, thanks :)

**Comment by heumn** [comment]
I am probably missing sometihng, but I could figure out what travis is complaining about? 🤔 

All tests and all projects are running just fine 

skjermbilde 2017-03-20 kl 17 24 17
skjermbilde 2017-03-20 kl 18 00 27
skjermbilde 2017-03-20 kl 18 01 14

**Comment by rnystrom** [comment]
@heumn looks great! The failures are the from the UI tests. I'm about to remove those b/c they are SO noisy. I don't think we've gotten any signal from them.

**Pull request closed without merging**
