### PR TITLE
Fix build docs script

### PR DESCRIPTION
**Pull request by zhubofei**
## Changes in this pull request
Fixed build-docs script. Workaround for #373

### CODE REVIEW

**Comment by zhubofei** [comment]
@jessesquires should I add a changelog entry for this one?

**Comment by Sherlouk** [comment]
Considerably cleaner than my attempt to fix this 🤔 Looks good!

**Comment by rnystrom** [comment]
@zhubofei dont worry about the changelog. Looks great!

**Comment by jessesquires** [comment]
nice! 💯  thanks @zhubofei !

**Pull request closed without merging**
