### PR TITLE
macOS support

### PR DESCRIPTION
**Pull request by insidegui**
## Changes in this pull request

Added support for macOS. The macOS target includes only the core diffing functionality so `IGListDiff` can be used on macOS apps.

I have not added the tests because I don't know how you're setting them up, maybe the same tests can be used by adding some `#if os(...)`s to the test files.

I have tested integration on iOS, tvOS and macOS using both Carthage and Cocoapods.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @insidegui ! This looks awesome 🎉

**Comment by jessesquires** [comment]
I want to pull this down and test locally, but I think we're good to go. 💯

**Comment by rnystrom** [comment]
Super super cool. Thanks @insidegui! Going to wait on @jessesquires for confirmation here.

**Comment by rnystrom** [comment]
@insidegui heads up, looks like there's a rebase issue atm

**Comment by insidegui** [comment]
Fixed! I also added some comments to make it more clear where the platform-specific and shared headers should go.

**Comment by jessesquires** [comment]
Hey @insidegui  -- quick update.

We *definitely* want this, but I'd like to target `2.x` release instead of `2.0`. We've been landing a few changes since this was opened and we have a few more. Once this settles down, let's rebase this and then we'll merge after `2.0`.

----------------

I'd like to follow-up with a `2.1` very shortly after `2.0` since this is an additive change. 

/> cc @rnystrom

**Comment by jessesquires** [comment]
@insidegui -- Ok, I think `master` has settled! Do you mind rebasing? 😄

**Comment by insidegui** [comment]
Squashed and rebased. Fixed Podspec to include `NSString` and `NSNumber` categories. I think that's it =)

**Comment by jessesquires** [comment]
I've created [milestone 2.1.0](https://github.com/Instagram/IGListKit/milestone/2) to track this and some follow-up work. 

We'll get this done immediately after the `2.0.0` release 💯

**Comment by jessesquires** [comment]
@insidegui - Actually, regarding #270 (the follow-ups), we could do a few of those things here if you want:

1. add the test target with tests
2. update `.travis.yml`
3. add the macro to simplify the `UIKit`/`Cocoa` imports

(For everything else, let's hold off so we can keep this PR small)

If you aren't interested in this stuff, no worries! 😄 We'll pick it up after we merge.

**Comment by insidegui** [comment]
I'll leave those to you 😄

**Comment by rnystrom** [comment]
@insidegui @jessesquires how we feeling here?

**Comment by jessesquires** [comment]
@rnystrom - Yep, I'm still waiting to land. Will do this later today or tomorrow. I want to do my follow-ups (#270) immediately after.

**Pull request closed without merging**
