### PR TITLE
#432 - Fixed incorrect `IGListScrollDelegate` property description

### PR DESCRIPTION
**Pull request by TimOliver**
G'day folks! I've been loving this project and have been itching for a chance to contribute! This is my first foray into submitting a PR to Facebook; I hope everything is in order.

Does this warrant being added to the `CHANGELOG`?

Thanks a lot!

## Changes in this pull request

In response to issue #432, this PR updates the description of `IGListScrollDelegate` in `IGListSectionController.h` to correctly match the method.

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @TimOliver ! 🎉

**Comment by Sherlouk** [comment]
@jessesquires Did something go wrong when importing this? The commit is in master but the description says 'Summary' and nothing else, and no issues were auto-closed!

**Comment by jessesquires** [comment]
Looks like something broke. Confirmed this is in `master`: 6e00787eb78c3b51d31186006f795f8a94d18b5d. Going to close.

Thanks Tom! 😉   @TimOliver

**Comment by jessesquires** [comment]
Also, cc @rnystrom in case we need some build bot fixes.

Ain't nobody got time for that.

**Comment by rnystrom** [comment]
Ugh. Ya the sync bot def screwed up. The summary is obvi wrong. I got some emails about it failing yesterday, but they went away...

**Pull request closed without merging**
