### PR TITLE
Fix defaults cmd issue on macOS 10.15

### PR DESCRIPTION
**Pull request by damozhang**
Use PlistBuddy Instead of defautls to extract the version from plist

## Changes in this pull request

Issue fixed: #1420 

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by lorixx** [comment]
Thanks @damozhang ! Can you rebase onto master again? The CLI lint issue should be fixed now, thanks!

**Comment by damozhang** [comment]
@lorixx I have done it. But I'm not sure if it works well.

**Comment by lorixx** [comment]
Please dont merge into stable, thanks!

**Comment by damozhang** [comment]
> Please dont merge into stable, thanks!

I'm sorry, first time do that.

**Pull request closed without merging**
