### PR TITLE
SPM number10 (#1487)

### PR DESCRIPTION
**Pull request by lorixx**
Summary:
## Changes in this pull request

 A better version of https://github.com/Instagram/IGListKit/issues/1465 =)

- SPM support with script-based generations.

- added macOS Catalyst support

 ### Generate SPM layout

1. From **project's root** run:

   `bash scripts/generate_spm_sources_layout.sh`

  2. Commit Changes

 Repeat those steps each time you delete/add the project's files. **Make sure** to have this CI step which will check that `generate_spm_sources_layout.sh` is not broken.

Issue fixed: https://github.com/Instagram/IGListKit/issues/1368 #1406

### Checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [ ] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

Pull Request resolved: https://github.com/Instagram/IGListKit/pull/1487

Reviewed By: candance

Differential Revision: D25562739

Pulled By: lorixx

### CODE REVIEW

**Comment by lorixx** [comment]
@3a4oT I rebased to the latest master and tried another time to resolve all the issues for SPM. However, I am still getting some errors from the build. Feel free to piggy back on my rebase and continue the work, I think we are getting really close here! I removed some of the IGListDiff Internal files as I believe they are just a blocker for us.

Test Plan:

1. Run `bash scripts/generate_spm_sources_layout.sh` to make sure we generate the symlinks;
2. Run `swift build`, <--- validate that we are seeing UIKit/UIKit.h not found errors here;
3. Run `swift package generate-xcodeproj && open ./IGListKit.xcodeproj` then in Xcode, hit the Run button, then confirmed there are build errors regarding to the Duplicate symbols.

Screen Shot 2021-08-14 at 11 40 26 AM



Screen Shot 2021-08-14 at 11 40 57 AM


Thanks @3a4oT !

**Comment by 3a4oT** [comment]
I'll take a look in the evening or later this week! Thanks!

**Comment by lorixx** [comment]
Thanks! Feel free to update it in your original PR in https://github.com/Instagram/IGListKit/pull/1487 !

**Comment by lorixx** [comment]
Update:

@3a4oT I shipped the Github Action PR https://github.com/Instagram/IGListKit/pull/1478 and working on resolving some of the CI issue, hopefully this saved you some time and focus on the SPM change. Thanks!

**Comment by lorixx** [comment]
@3a4oT Once you incorporate my change in this PR, I will close this PR out and we can consolidate all in your PR https://github.com/Instagram/IGListKit/pull/1487

**Comment by lorixx** [comment]
Closing this experimental PR https://github.com/Instagram/IGListKit/pull/1487

**Pull request closed without merging**
