### PR TITLE
Remove SwiftLint

### PR DESCRIPTION
**Pull request by rnystrom**
## Changes in this pull request

Follow up from #837. Too much noise to keep working, and cost to maintain in an examples app is too high.

### CODE REVIEW

**Comment by heumn** [comment]
are you open to me adding SwiftFormat in a PR? :)

**Comment by rnystrom** [comment]
@heumn lets hold on that for now. Idk if there's a lot of value in adding/maintaining all these tools just for a sample app. Once we start using Swift in the main lib, then it'll be much much much more important (IMO).

**Comment by heshamsalman** [comment]
@rnystrom LGTM as a solution. Could reducing the # of active rules also achieve the same effect?

**Comment by heumn** [comment]
Got it and agreed :)

**Comment by rnystrom** [comment]
@heshamsalman that's a good point. Maybe that'd be simpler than gutting it?

**Comment by jessesquires** [comment]
I agree with @heshamsalman  -- I don't think we should just gut this. Let's relax the rules instead 😄

**Pull request closed without merging**
