### PR TITLE
Create a grid layout for IGList

### LINKED ISSUE #3: Add a UICollectionViewLayout similar to flow layout that doesn't newline sections, a section-based grid layout
If you use `UICollectionViewFlowLayout` and your item controllers return individual cells that should be in a grid (see Instagram Explore tab), they will stick vertically in new rows instead of fitting into rows/columns as if they were all in the same section.

We have this internally for our Explore product (which uses `IGListKit`) but the layout is pretty specific for that instance. It'd be amazing to have a general layout as part of the framework.

### PR DESCRIPTION
**Pull request by zhubofei**
Rebase from #140:

Create a flow layout for IGList that does not newline sections. Closes #3

- [x] Minimum inter-item spacing
- [x] Minimum line spacing
- [x] Constant item size with constant layout time
- [x] Update layout on insert/delete/move
- [x] Unit Test

### CODE REVIEW

**Comment by zhubofei** [comment]
Still no coverall 😂

**Comment by jessesquires** [comment]
Thanks @zhubofei ! 💯

**Comment by jessesquires** [comment]
@rnystrom -- Are we targeting this for the 2.0 release?

**Comment by rnystrom** [comment]
@jessesquires ya I think so, sound good? Importing today

**Comment by jessesquires** [comment]
@rnystrom - don't forget to update the CHANGELOG 😄.

Maybe we could merge #234 first though? 😊

**Comment by rnystrom** [comment]
Updated changelog, fixed some compiler errors from our strict build settings, and created a local var for `self.collectionView` in the attributes-for-rect method. Landing now.

**Pull request closed without merging**
