### PR TITLE
Print file name when searching for broken links

### PR DESCRIPTION
**Pull request by Sherlouk**
## Changes in this pull request

Wasn't sure how to make it a one line wonder, so probably could be improved -- but slapped it into a while loops and print name before triggering the `markdown-link-check`.

Refers to https://github.com/Instagram/IGListKit/pull/344#issuecomment-268163911

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Sherlouk** [comment]
Investigating error - linting passed

**Comment by jessesquires** [comment]
@Sherlouk awesome! 🎉 thanks!

**Comment by jessesquires** [comment]
let's wait for ci to pass

**Comment by Sherlouk** [comment]
Passed 🎉 

And who said I couldn't do shell? 😏

**Comment by jessesquires** [comment]
@Sherlouk

**Comment by Sherlouk** [comment]
Who? Me!?

**Pull request closed without merging**
