### PR TITLE
Clean up examples, update Gemfile, update travis

### LINKED ISSUE #202: Fixup Examples directory
Will need to tweak `.travis.yml` too.

Follow up from #141 

```
|-- Examples/
    |-- Examples-iOS/
    |-- Examples-tvOS/
```

### PR DESCRIPTION
**Pull request by jessesquires**
- Clean up examples directory to be like the following: (closes #202)

```
|-- Examples/
    |-- Examples-iOS/
    |-- Examples-tvOS/
```

- Update travis to [Xcode 8.1](https://blog.travis-ci.com/2016-11-15-xcode-81-is-here)
- Update travis for new examples directories
- Update examples Podfiles
- Run `pod install` everywhere
- Update Gemfile for CocoaPods 1.1.1

> **NOTE:** ⚠️ No code changes, just moves.

### CODE REVIEW

**Comment by jessesquires** [comment]
If CI passes then 🎉

**Comment by Sherlouk** [comment]
@jessesquires Do we need to update the Changelog & Readme files as they have relative references to files that will no longer exist once merged

**Comment by jessesquires** [comment]
Patched this internally via 879260b417fe67ac4b4edc9b04f7729949f3634f

**Comment by Sherlouk** [comment]
@jessesquires Still broken links in both README.md & CHANGELOG.md

Want me to do a quick PR?

**Comment by jessesquires** [comment]
@Sherlouk -- yep I forgot that! 😊  A PR would be great 👍

**Pull request closed without merging**
