### PR TITLE
Deflake Travis jobs

### PR DESCRIPTION
**Pull request by rnystrom**
Too much noise, really want to see ✅ on PRs instead of having to fish to see it was just the UI tests again.

### CODE REVIEW

**Comment by rnystrom** [comment]
Lol and the tests still fail. Looks like its not the UI tests. Found some info here:

https://github.com/travis-ci/travis-ci/issues/6422

Will dig more and figure out how to chill these tests out.

**Comment by Sherlouk** [comment]
Just disable all the tests :trollface:

**Comment by jessesquires** [comment]
@rnystrom ugh. yeah -- all the important issues opened at travis-ci have been there for like a year

**Comment by jessesquires** [comment]
everyone: "all the things are broken. still..."

travis-ci: "meh"

**Comment by rnystrom** [comment]
Seems like we might be able to reduce noise by adding `travis_retry` before each `xcodebuild`. That might hurt build times _even more_ though...

The other solution [linked](http://stackoverflow.com/questions/37922146/xctests-failing-on-physical-device-canceling-tests-due-to-timeout/40790171#40790171) in that issue is to separate building and testing 

```
> xcodebuild clean build build-for-testing <other options>
> xcodebuild test-without-building <other options>
```

That has the most likes/hearts so it must be right?

**Pull request closed without merging**
