### PR TITLE
Add NSObject Conformance to IGListUpdatingDelegate

### PR DESCRIPTION
**Pull request by Adlai-Holler**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
@jessesquires 2.2 or 3.0?

**Comment by jessesquires** [comment]
@rnystrom 🤔  Hm... 2.2 for ObjC. Does this break anything in Swift? (I suspect yes, which case, 3.0)

**Comment by rnystrom** [comment]
It would if you write your own Swift `IGListUpdatingDelegate`. Previously you could do
```swift
class MyCustomUpdater: IGListUpdatingDelegate { ... }
```

But now it probably has to be

```swift
class MyCustomUpdater: NSObject, IGListUpdatingDelegate { ... }
```

I think.

**Comment by jessesquires** [comment]
@rnystrom right - let's double check

**Comment by Adlai-Holler** [comment]
BTW fellas I did double-check, and it's true.

**Pull request closed without merging**
