### PR TITLE
Cleanup layout

### PR DESCRIPTION
**Pull request by jessesquires**
Replaces #243 

---------------------

- Clean up GridLayout + docs
- Remove GridLayout scroll direction, not used/supported?
- Fix some file target membership issues
- Add GridLayout to umbrella header
- "Sort by name" on xcode project directories
- crtl-I auto format in xcode
- re-gen docs

### CODE REVIEW

**Comment by zhubofei** [comment]
@jessesquires IMO, setting default itemSize to (0, 0) instead of (100, 100) may be a better choice. Because if itemSize is set to non-zero, the layout would assume that all the cells are fix-sized.

**Comment by jessesquires** [comment]
@zhubofei Ahh.. ok. Docs didn't specify that. 😉 

After this merges, want to submit a PR to fix + add docs ? 😄

**Comment by jessesquires** [comment]
Ah actually, that change broke tests. I'll fix this up.

**Comment by zhubofei** [comment]
Thank you 😅. I'll be more careful with initialization next time.

**Pull request closed without merging**
