### PR TITLE
Create private method in IGListStackedSectionController to get relative index

### LINKED ISSUE #272: Create private IGListStackedSectionController method to get relative index
There are so many calls where we get the child section controller offset and add the index:

https://github.com/Instagram/IGListKit/blob/master/Source/IGListStackedSectionController.m#L164-L165

There should be a method opposite of [localIndexForSectionController:index:](https://github.com/Instagram/IGListKit/blob/master/Source/IGListStackedSectionController.m#L106-L110) that _adds_ the offset and index.

Need to refactor all places we do `index + offset` to use this method instead.

### PR DESCRIPTION
**Pull request by bmeverett**
## Changes in this pull request

Adds `relativeIndexForSectionController: fromLocalIndex:` method to add index to offset.
Refactors all `index + offset` to use the method.
Closes #272  

Should I add tests? I figured the current tests would cover this change.
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
Woot! That was fast. @bmeverett mind rebasing and updating the `offset + index` in e5afb5b4d0cfc70a2736b02279b6bc239ddf1e5d as well?

**Comment by bmeverett** [comment]
@rnystrom hopefully that's what you wanted

**Comment by rnystrom** [comment]
@bmeverett ack, it looks like the commits got out of sync in the rebase and it pulled in @jessesquires's commit here. You might be able to fix everything by doing:

```
$ git rebase -i master HEAD~3
```

Then move Jesse's commit ahead of your two. We want this PR to be just your commits and not a mix of others.

**Comment by jessesquires** [comment]
💯 

Alternatively -- sometimes it's easier to just open a new PR 😅

**Comment by bmeverett** [comment]
@rnystrom will I have to do a force push after rebase then? Here's what the log and status look like
screen shot 2016-12-02 at 6 31 15 am


@jessesquires I pushed another branch [t2](https://github.com/bmeverett/IGListKit/tree/t2) and it looks like it stills has your commit in it.

Sorry guys, but what should I do?

**Comment by rnystrom** [comment]
@bmeverett no worries! I'm going to close this one and we'll use #275

**Pull request closed without merging**
