### PR TITLE
Clean iOS8 system version code

### PR DESCRIPTION
**Pull request by kinarobin**
## Changes in this pull request

 Just clean useless code.

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by lorixx** [comment]
Looks like the build failed, can you fix the build issue? thx!

**Comment by kinarobin** [comment]
When run `./scripts/setup.sh` , with this error, any suggestions?





```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A602)
       Xcode : 11.2.1 (11B53)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories :  master - git - https://github.com/CocoaPods/Specs.git @ 719bff08484e5144379e08fc966272084072604a
               trunk - CDN - https://cdn.cocoapods.org/
```

**Comment by kinarobin** [comment]
Just with #1392 merge, I will update new code.

**Comment by lorixx** [comment]
I abandoned my PR since @koenpunt had already updated the cocoapods version to the latest

**Pull request closed without merging**
