### PR TITLE
Skip forcing layout when UICollectionView is invisible #trivial

### PR DESCRIPTION
**Pull request by jiecongwang**
## Changes in this pull request

Issue fixed: # https://github.com/Instagram/IGListKit/issues/1267

### Checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [ ] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
@maxoll Any chance you could help take a look at this (details in #1267). I'm not sure how much this would help us w/ perf, if we should test this, or if there's any data we can pull to verify if this happens. I'm pretty hesitant to merge w/out understanding the impact + risks.

**Comment by jiecongwang** [comment]
Our issue only happens when the uicollectionview.window == nil. It is unnecessary to call [collectionview layoutIfneeded] when uicollectionview.window == nil, the collectionview has already existed from current window and it is invisible.

**Comment by rnystrom** [comment]
Just FYI I made this an experiment so we can test it out in Instagram before releasing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jiecongwang** [comment]
@rnystrom You mean you will test removing [collectionview layoutifneeded] in the fallback method when UICollectionView window is nil in instagram to see how it goes?

**Pull request closed without merging**
