### PR TITLE
Updated script to pin SwiftLint version

### PR DESCRIPTION
**Pull request by heshamsalman**
## Changes in this pull request

Issue fixed: #847 

Pinned SwiftLint to 20.1

### CODE REVIEW

**Comment by jessesquires** [comment]
Awesome! 🙌 

Thanks @heshamsalman ! 💯

**Comment by rnystrom** [comment]
+1 @jessesquires to putting it someplace shared

**Comment by heshamsalman** [comment]
@jessesquires I don't see why not 👍

**Comment by jessesquires** [comment]
🎉

**Pull request closed without merging**
