### PR TITLE
Example using self sizing cells

### LINKED ISSUE #149: Self-sizing cell example
Both #80 and #143 show that self-sizing cells with `IGListKit` is a little hard to follow. I think we need to get a working example. Some things that would be great to see:

- Setting up self-sizing cells **in code**
- Using storyboards

### PR DESCRIPTION
**Pull request by rnystrom**
## Changes in this pull request

Adding an example using self sizing cells (`estimatedSize` API of `UICollectionViewFlowLayout`) both in code and from cells in nibs. I assume cells in storyboards would follow the same AL design patterns as nibs, so I left out storyboards.

simulator screen shot nov 8 2016 11 55 04 am

Fixes #149

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
cc @valeriyvan to check my Swift-foo 😄

**Comment by valeriyvan** [comment]
👍

**Comment by rnystrom** [comment]
Updated w/ full width auto-height cell

**Comment by HarshilShah** [comment]
Layouts with self-sizing cells break completely when the `IGListSectionController`’s left or right `inset` is nonzero. Is this a known bug? Any workarounds?

**Comment by rnystrom** [comment]
@HarshilShah what is the break? Crash? Layout is wrong?

**Comment by HarshilShah** [comment]
@rnystrom Sure thing, filing an issue

**Pull request closed without merging**
