### PR TITLE
Add Swiftlint #trivial

### PR DESCRIPTION
**Pull request by heshamsalman**
Replaces #642

Issue ref: #394 

Integrates SwiftLint into DangerBot.
You may want to append a ?w=1 to the end of the files-changed url to exclude whitespace-only changes.

- [ ] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [ ] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

#trivial

### CODE REVIEW

**Comment by jessesquires** [comment]
@rnystrom -- still having trouble getting this imported. any updates?

**Comment by rnystrom** [comment]
Ok so this is adding about 35mb to the repo from including the SwiftLint framework 3x from each of the examples. Wow. Our internal tools flagged this and wont let us import it b/c of the size.

I'm not totally sure what the best course of action here should be. Obviously the main issue is having 3x separate example projects, each with their own `Podfile`, and the fact that we check in all Pod data.

Couple options:

- We drop all the SwiftLint stuff and just keep the lint changes to .swift files
- We update all of the examples to be a single project/workspace so we only SwiftLint import once
- We drop this altogether ☹️

**Comment by heshamsalman** [comment]
@rnystrom surprised it's 35mb. 
I think short-term, the right move may be to take the changes to the `.swift` files and drop SwiftLint from the example projects -- it won't flag errors during development of the Example project, but the bot should still flag errors on the PR. 

Restructuring into one `xcworkspace` sounds like the right longer-term move to me.

**Comment by Sherlouk** [comment]
Another option is to get the framework (1 version of it) store that in a directory (e.g. Examples/Swiftlint) and then reference that with a built script from all 3 projects. (So stop using CocoaPods to get Swiftlint).

I'd honestly prefer this!
@rnystrom  @heshamsalman

**Comment by jessesquires** [comment]
I think @Sherlouk 's idea is good.

That's how the local `IGListKit` pod is working -- all examples just reference `../../IGListKit`

**Comment by heshamsalman** [comment]
Occam's Razor 😎
Seems like the right move to me. I'll make the change late Friday or Sunday 👍

**Comment by jessesquires** [comment]
cc @rnystrom ?

**Comment by rnystrom** [comment]
On board w/ @Sherlouk's plan, sounds great!

**Comment by heshamsalman** [comment]
@Sherlouk @jessesquires @rnystrom 

Should be a good deal smaller now. 👍

**Comment by Sherlouk** [comment]
Changes look a lot nicer, will leave it to the insta crew to check on Phabricator! Hopefully we can get it in 🙏

**Comment by Sherlouk** [comment]
@rnystrom @jessesquires Think we could try and see if Phabricator will except this some time this week? Would be nice to get this in (and I get that it's a pain to keep rebasing 😅)

**Comment by jessesquires** [comment]
@Sherlouk - yep, everything looks alright to me!

**Comment by heshamsalman** [comment]
Ayyy 👍

**Comment by jessesquires** [comment]
Ok, bad news:

So imported succeed but land failed internally because the binary files are too large. 😞 

The best path forward is probably to run this on CI, but *not* include `SwiftLint` in the repo? Not 100% on what the best option is. 

@rnystrom is out for a bit, when he returns we can sort this out. 👍 

Sorry for the churn @heshamsalman ! 😅

**Comment by heshamsalman** [comment]
@jessesquires I could alternatively change the SwiftLint script to rely on a user's `HomeBrew` installed copy of SwiftLint (instead of a locally referenced binary), and echo installation instructions if they don't have it installed?

**Comment by jessesquires** [comment]
@heshamsalman -- that sounds awesome! Let's **definitely** do that.

That's how we handle `jazzy`. Use must have it installed.

**Comment by jessesquires** [comment]
@heshamsalman -- because of how the importing system works, we'll need to open a new PR 😄

**Comment by heshamsalman** [comment]
@jessesquires haha classic. I'll re-open soon

**Comment by jessesquires** [comment]
thanks so much @heshamsalman ! 🎉

**Comment by BasThomas** [comment]
> User must have it installed. (Though we don't provide a helpful message about how to install. that would be nice)

Might be a good idea to create an issue for that? :)

**Comment by jessesquires** [comment]
@BasThomas Yep! 😊

**Comment by BasThomas** [comment]
Created #744. :)

**Pull request closed without merging**
