### PR TITLE
Disable iOS 9.3 tests

### PR DESCRIPTION
**Pull request by rnystrom**
## Changes in this pull request

These tests are timing out all the time. ☠️ 

Issue fixed: #683

### CODE REVIEW

**Comment by rnystrom** [comment]
lol these CI jobs are just trolling me now

**Comment by jessesquires** [comment]
lol

**Comment by rnystrom** [comment]
@jessesquires do we need to bump iOS versions? Here's the output:

```
$ if [ $RUN_TESTS == "YES" ]; then xcodebuild build build-for-testing -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES | xcpretty -c; xcodebuild analyze test-without-building -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES | xcpretty -c; else xcodebuild build analyze -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c; fi
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ OS:10.2, name:iPad Air 2 }
	Unsupported device specifier option.
	The device “My Mac” does not support the following options: OS
	Please supply only supported device specifier options.
	Available destinations for the "IGListKit" scheme:
		{ platform:iOS Simulator, id:009C8748-E16A-4387-81C1-C8C55E5DE71E, OS:10.3, name:iPad Air }
		{ platform:iOS Simulator, id:F2BE0078-A556-467F-A458-588C1F94C321, OS:10.3, name:iPad Air 2 }
		{ platform:iOS Simulator, id:927B3C76-1FF2-437D-B922-0202906750E1, OS:10.3, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:10C30121-2C7C-4D15-B432-F8B2CE5FC416, OS:10.3, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:900578B5-4EB3-429A-B746-21CD15A280F0, OS:10.3, name:iPhone 5 }
		{ platform:iOS Simulator, id:FD1C5C0E-19DE-4E77-A5DF-DA7BE930C5DB, OS:10.3, name:iPhone 5s }
		{ platform:iOS Simulator, id:DD5E88FF-1AD0-4ADD-A6F0-162759432055, OS:10.3, name:iPhone 6 }
		{ platform:iOS Simulator, id:3036ACC2-7793-4C93-991D-FBD3F71987FF, OS:10.3, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:01A4566E-C24F-48A8-AFBD-2612205C0E8C, OS:10.3, name:iPhone 6s }
		{ platform:iOS Simulator, id:0004671C-F9BB-4755-A2B6-1C2A6844401D, OS:10.3, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:2437D975-7A64-4F01-B8C9-2510D4DAF5AD, OS:10.3, name:iPhone 7 }
		{ platform:iOS Simulator, id:32CF67DB-D589-4143-9EB4-E534EB51877B, OS:10.3, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:09AAB3B1-8423-4B8C-BC6A-1B094341C07A, OS:10.3, name:iPhone SE }
	Ineligible destinations for the "IGListKit" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ OS:10.2, name:iPad Air 2 }
	Unsupported device specifier option.
	The device “My Mac” does not support the following options: OS
	Please supply only supported device specifier options.
	Available destinations for the "IGListKit" scheme:
		{ platform:iOS Simulator, id:009C8748-E16A-4387-81C1-C8C55E5DE71E, OS:10.3, name:iPad Air }
		{ platform:iOS Simulator, id:F2BE0078-A556-467F-A458-588C1F94C321, OS:10.3, name:iPad Air 2 }
		{ platform:iOS Simulator, id:927B3C76-1FF2-437D-B922-0202906750E1, OS:10.3, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:10C30121-2C7C-4D15-B432-F8B2CE5FC416, OS:10.3, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:900578B5-4EB3-429A-B746-21CD15A280F0, OS:10.3, name:iPhone 5 }
		{ platform:iOS Simulator, id:FD1C5C0E-19DE-4E77-A5DF-DA7BE930C5DB, OS:10.3, name:iPhone 5s }
		{ platform:iOS Simulator, id:DD5E88FF-1AD0-4ADD-A6F0-162759432055, OS:10.3, name:iPhone 6 }
		{ platform:iOS Simulator, id:3036ACC2-7793-4C93-991D-FBD3F71987FF, OS:10.3, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:01A4566E-C24F-48A8-AFBD-2612205C0E8C, OS:10.3, name:iPhone 6s }
		{ platform:iOS Simulator, id:0004671C-F9BB-4755-A2B6-1C2A6844401D, OS:10.3, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:2437D975-7A64-4F01-B8C9-2510D4DAF5AD, OS:10.3, name:iPhone 7 }
		{ platform:iOS Simulator, id:32CF67DB-D589-4143-9EB4-E534EB51877B, OS:10.3, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:09AAB3B1-8423-4B8C-BC6A-1B094341C07A, OS:10.3, name:iPhone SE }
	Ineligible destinations for the "IGListKit" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
```

**Comment by rnystrom** [comment]
Ok I'm getting annoyed.

I read through [the travis Xcode guide](https://docs.travis-ci.com/user/languages/objective-c/) and can see that all of our simulator+device pairings are supported in Xcode 8.3. Also all of our setup:

- `osx_image: xcode8.3`
- `IOS_SDK=iphonesimulator10.3`
- `TVOS_SDK=appletvsimulator10.2`
- `MACOS_SDK=macosx10.12`

is [supported](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8.3).

If we have UI and unit tests disabled for all of these builds, should we just remove them?

**Comment by rnystrom** [comment]
Looks like a Travis issue https://github.com/travis-ci/travis-ci/issues/7638

**Comment by jessesquires** [comment]
we should still build for each of these iOS versions, which will catch:

1. clownly PRs that don't compile
2. using iOS 10 only APIs
3. build warnings (which we treat as errors, right?)

(i think)

if we're going to disable everything, we might as well stop using travis altogether

**Comment by Sherlouk** [comment]
Would it be worth trying out a free build with Circle/Buddybuild? Appears to me this issue is more with Travis than it is the tests (mostly)

**Comment by jessesquires** [comment]
Xcode is also just unreliable on CI, as far as I know

**Comment by Sherlouk** [comment]
Oh yeah definitely not disagreeing with you there Jesse, but a slow platform with incorrect settings can also not help. Best to rule it out at least?

**Comment by rnystrom** [comment]
@jessesquires I left them as commented builds b/c of the Travis CI issue (their xcode 8.3 image doesn't include any simulator but iOS 10.3). I'd rather get working signal and then uncomment those builds once they fix it.

**Comment by jessesquires** [comment]
> their xcode 8.3 image doesn't include any simulator but iOS 10.3

🤔  that doesn't make sense...

I'm building everything on my Xcode8.3 projects:
https://travis-ci.org/jessesquires/JSQCoreDataKit

**Comment by jessesquires** [comment]
Did someone set the project minimum targets to 10.3??

**Comment by heshamsalman** [comment]
screen shot 2017-04-24 at 8 05 37 pm

**Comment by jessesquires** [comment]
@heshamsalman - what about the actual targets though?

(also need to check example projects)

**Comment by heshamsalman** [comment]
@jessesquires looks like for the examples the iOS target minimum is 9.3, macOS @ 10.10

**Comment by rnystrom** [comment]
@jessesquires [check out the issue I posted above](https://github.com/travis-ci/travis-ci/issues/7638) (4 days old)

Also various build failures of ours:

[this one](https://travis-ci.org/Instagram/IGListKit/jobs/224744886)

```
Unable to find a destination matching the provided destination specifier:
		{ OS:10.1, name:iPhone 6s }
```

[or this one](https://travis-ci.org/Instagram/IGListKit/jobs/224744883)

```
 Unable to find a destination matching the provided destination specifier:
		{ OS:9.2, name:iPhone 6s }
```

[or this](https://travis-ci.org/Instagram/IGListKit/jobs/224744878)

```
Unable to find a destination matching the provided destination specifier:
		{ OS:8.3, name:iPhone 6 }
```

The last JSQCoreDataKit build was [20 days ago](https://travis-ci.org/jessesquires/JSQCoreDataKit/builds), have you tried pushing anything in the last few days?

**Comment by jessesquires** [comment]
@rnystrom -- ugh. what. the. fuck.

**Comment by jessesquires** [comment]
ok. fuck travis-ci. let's use something else.

**Comment by rnystrom** [comment]
We can try [this comment patch too](https://github.com/travis-ci/travis-ci/issues/7638#issuecomment-297060273)

But I'm w/ @jessesquires, Travis has been a pain in the ass.

**Comment by heshamsalman** [comment]
CircleCI may be worth investigating -- `.travis.yml` files translate pretty easily into `circle.yml` files.

**Comment by amonshiz** [comment]
Convert the world to BUCK and then move all FB OSS to a public Phabricator. That should work, right?

**Comment by jessesquires** [comment]
looks like this was fixed:
https://twitter.com/travisci/status/857306346538106880

🎉

**Comment by rnystrom** [comment]
Good ol' timeouts are back. At least the sims are there.

**Comment by jessesquires** [comment]
@rnystrom lol -- at least, i don't think this is travis-ci's fault but xcode's

should we just set tests to `NO` for 9.x ?

**Comment by rnystrom** [comment]
@jessesquires ugh, probably... I really want to run those tests since internally we only CI latest, but passing-signal is better than noise.

**Pull request closed without merging**
