### PR TITLE
Fix typo in connecting data source code in README

### PR DESCRIPTION
**Pull request by chrisamanse**
## Changes in this pull request

Only README.md was changed. Fixed the typo in example code for connecting data source (replace opening parenthesis with whitespace).

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @chrisamanse !

**Comment by rnystrom** [comment]
@chrisamanse actually needs to be `sectionControllerFor object` (omit the `Object`). We already started the import process so either we can fix it on ourselves or just update the rev from your changes.

**Comment by chrisamanse** [comment]
@rnystrom Done. Replaced the commit with the correct changes.

**Comment by rnystrom** [comment]
@chrisamanse thanks! Looks like our import doesn't auto update, we'll make sure this syncs correctly.

**Pull request closed without merging**
