### PR TITLE
Change paths to path

### PR DESCRIPTION
**Pull request by zhubofei**
## Changes in this pull request
Should map be a map of `IndexPath`s instead of arrays of `IndexPath`s? Also, we might need some unit tests on this part. I don't think it's covered. 

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by zhubofei** [comment]
@rnystrom Done

**Comment by zhubofei** [comment]
@rnystrom @jessesquires After adding the test, I find this bug isn't that trivial😆. Should I add a changelog for it?

**Comment by rnystrom** [comment]
@zhubofei yes please! I need to do a deeper audit to make sure this doesn't break anything haha.

**Comment by lorixx** [comment]
@zhubofei Thanks for the fix, what I dont understand is that it seems like the current production code is not affected by this bug at all, do u have any theory why this is the case?

**Pull request closed without merging**
