### PR TITLE
Release 2.1.0 prep

### PR DESCRIPTION
**Pull request by jessesquires**
Prepping for `2.1.0`

- [x] Bump version numbers
- [x] Rebase this branch after remaining PRs are closed
- [x] Run `pod install` (**must be done internally**)
- [x] Re-gen docs

### CODE REVIEW

**Comment by Sherlouk** [comment]
Out of interest, why 2.0.1 and not 2.1.0 for Podspec/Project file?

Based on the format major.minor.patch?

**Comment by rnystrom** [comment]
@jessesquires see @Sherlouk's comment, I think the version is wrong

**Comment by rnystrom** [comment]
- [ ] Confirm badge updates with macOS (should happen automatically after CocoaPods updates)

**Comment by Sherlouk** [comment]
- [ ] Update version numbers in README.md and Installation Guide files

**Comment by jessesquires** [comment]
lol oops 😊

**Comment by jessesquires** [comment]
@Sherlouk -- we can keep the guides as `'~> 2.0.0'` (the `~>` will pull 2.x up to, but not including 3.0)

**Comment by Sherlouk** [comment]
@jessesquires Interesting, didn't know that.
Because we added the Subspec in 2.1.0, will it still work for `IGListKit/Diffing`? I didn't take that into consideration when testing.

**Comment by jessesquires** [comment]
@Sherlouk - yep, it shouldn't matter as far as i know

**Pull request closed without merging**
