### PR TITLE
Fix TV example

### PR DESCRIPTION
**Pull request by rnystrom**
## Changes in this pull request

TV example build was failing (badge red). Fixed w/ `pod install`.

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rnystrom** [comment]
Waiting on CI ✅

**Comment by Sherlouk** [comment]
Would it be worth having a shell script at `Examples/` level which pod installs for all examples (future proofing for what ever is to come, but currently does iOS and tvOS)?

**Comment by rnystrom** [comment]
@Sherlouk I thought about that, only downside is that if we do that during CI builds it'll hide builds that are failing after a fresh `git clone` or download of the repo. IMO everything (workspace, tests, and examples) should be build-and-runnable immediately after download. If we don't check them w/ CI then we wont notice until someone files and issue.

**Comment by jessesquires** [comment]
@rnystrom -- we should run pod install on the other examples too

**Pull request closed without merging**
