### PR TITLE
Change NSUInteger to NSInteger in public API

### PR DESCRIPTION
**Pull request by zhubofei**
#200

### CODE REVIEW

**Comment by rnystrom** [comment]
🔥 

Gonna wait on CI to go ✅

**Comment by rnystrom** [comment]
Duped w/ #205, this one is much lighter but I'll give that PR a chance to cleanup before merging since it was chronologically first in.

**Comment by zhubofei** [comment]
@rnystrom Sure😊

**Comment by jessesquires** [comment]
Thanks @zhubofei ! 🙌

**Pull request closed without merging**
