### PR TITLE
travis voodoo

### PR DESCRIPTION
**Pull request by jessesquires**
✨ magic ✨ 

We forgot the lamb's blood last time. 

- run UI tests on ~~iOS 9, not iOS 10~~ iOS 10.1
- only pod lint once 
- only build examples for major releases, not point releases. (new APIs are rarely introduced in point releases)

### CODE REVIEW

**Comment by jessesquires** [comment]
in response to https://github.com/Instagram/IGListKit/pull/295#issuecomment-265334736 😄

**Comment by jessesquires** [comment]
lol. whoops. can't run UI tests on iOS 9 because of the extensions. switched to 10.1 and updated original comment.

locally, Xcode flips the fuck out when you try to run UI tests on iOS 9 when today extensions. omg.

**Comment by Sherlouk** [comment]
> ui test fixes /shrug/ lol omfg

Can we take a moment to appreciate the commit message? 😂

**Comment by rnystrom** [comment]
Green, landing

**Pull request closed without merging**
