### PR TITLE
Update .travis.yml and lint.sh, try to fix #1060 and lint errors #trivial

### LINKED ISSUE #1060: [Travis] cannot find cocoapods
travis seems to be barfing on installing CP. not sure why.

https://travis-ci.org/Instagram/IGListKit/jobs/331557269#L428

```
Could not find proper version of cocoapods (1.4.0) in any of the sources
```

### PR DESCRIPTION
**Pull request by jessesquires**
project:
- fix file target membership issues in framework targets and test targets
- fix private/internal header imports, which shouldn't be `<IGListKit/` apparently
- fix static analyzer errors

travis:
- always install latest swiftlint
- ~~don't cache bundler, attempts to fix #1060~~
- remove markdown link check

swiftlint:
- make script non-failing if *any* version of swiftlint is installed
- warning if incorrect version is installed
- fail if not installed
- remove `scripts/generate_ci_yaml.rb`, we can just set the config file path directly

### CODE REVIEW

**Comment by rnystrom** [comment]
Lol now internal synced changes breaking example projects.

never ending

**Comment by rnystrom** [comment]
Will need a rebase on #1069

**Comment by jessesquires** [comment]
updated cc @rnystrom @Sherlouk

**Comment by jessesquires** [comment]
(rebased on master too, so this should fix all the things and make travis ✅ -- hopefully 🤞 )

**Comment by rnystrom** [comment]
@jessesquires could you run `pod install` on the root repo? That should fix it. I missed that one.

Btw should we add root and example pod install as a pre step on CI?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Added #1074, @jessesquires lmk if you'd like me to land that first and you can rebase, or just `pod install` in the IGLK dir as part of this PR.

**Comment by jessesquires** [comment]
@rnystrom perfect. Let's land yours, then i'll rebase 😄

**Comment by jessesquires** [comment]
rebased

**Comment by jessesquires** [comment]
ran `bundle update`

**Comment by jessesquires** [comment]
ok. hopefully this is all good now.

**Comment by jessesquires** [comment]
@rnystrom pushing more updates now. FYI file target membership is totally fucked in the project.

Also, that new layout thing wasn't in the umbrella header.

**Comment by jessesquires** [comment]
@rnystrom Looks like appleTV tests are legitimately broken

**Comment by jessesquires** [comment]
Ok. confirmed everything builds and runs successfully now.

Only open issue is tvOS tests, but let's defer that for another PR

**Comment by rnystrom** [comment]
Go go go Travis, I believe in you!

**Comment by jessesquires** [comment]
@rnystrom there are legitimate test failures everywhere.

"does not respond to selector" because of API availability (iOS 10+ APIs, etc.)

**Comment by rnystrom** [comment]
@jessesquires those appear to only be warnings, the only failure I can see in the logs is

```
Could not find proper version of cocoapods (1.4.0) in any of the sources
```

Right?

**Comment by jessesquires** [comment]
> we're so close

Ha

No keep scrolling down.

https://travis-ci.org/Instagram/IGListKit/jobs/335741172#L4525

**Comment by jessesquires** [comment]
Also, this markdown deadlink checking is still searching `vendor/`.

I feel like this creates more noise than value. Can we remove?

cc @Sherlouk

**Comment by Sherlouk** [comment]
@jessesquires Obviously you can remove it, no questions need be asked, but I do feel the script adds value if someone who knew bash were to make it function correctly!

**Comment by jessesquires** [comment]
@Sherlouk - want to open an issue to revisit add this back eventually?

**Comment by rnystrom** [comment]
@jessesquires should we just drop iOS 8 support? Those failures show up from enabling unit and UI tests on iOS 8.4 👴

**Comment by jessesquires** [comment]
Hm.. @rnystrom doesn't IG still support iOS 8 though?

**Comment by jessesquires** [comment]
If we decide to drop it, then we'd need to do it for `4.0` because that's a breaking change.

**Comment by rnystrom** [comment]
@jessesquires nope min 9. Can we just disable running the tests in iOS 8? The Test suite explicitly tests APIs that are available in 9+ (IGLK works in 8 still).

Sounds good on dropping in 4.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
> nope min 9, dropped 8 last summer.

Oh nice! 👌 

Sounds good.

**Comment by jessesquires** [comment]
I went ahead and just completely removed that iOS 8 build entry.

**Comment by rnystrom** [comment]
Alright, I pulled `master` and everything is broken. I'll have a PR up shortly fixing builds + tests for all the busted stuff.

**Comment by jessesquires** [comment]
Ok. Last issue is that `Danger` was failing builds, I think because of Swiftlint configuration issues. Just pushed changes to address that

**Comment by jessesquires** [comment]
@rnystrom this is rebased and ready to go. let's merge this fucking thing.

**Comment by jessesquires** [comment]
Outstanding issues:

- Still no idea why travis-ci can't find CocoaPods 1.4.0 (My other projects are fine)
- Danger is failing builds but it's not clear why. (Confirmed it's not Swiftlint)

**Comment by jessesquires** [comment]
Ok, I ran `Danger` locally. Only one "error":

```
Errors:
- [ ] Any source code changes should have an entry in CHANGELOG.md.
```

But why isn't the bot commenting? 

@rnystrom Did FB internal break something?

**Comment by rnystrom** [comment]
@jessesquires I’ll check up on the hot, but if we add #trivial to the title and rebuild that should remove the Danger error.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Nothing is #trivial when travis/CI is involved :trollface:

**Comment by jessesquires** [comment]
Looked at logs. All builds are green except for `iOS 9.3` where XCTExpectations timeout.

Then Danger is failing them all at the end.

**Comment by rnystrom** [comment]
Testing 9.3 stuff locally. Added #trivial and restarted builds.

(also is it just me or is Travis fast af now?)

**Comment by rnystrom** [comment]
Debugging iOS 9.3 failures right now. Could be real.

**Comment by jessesquires** [comment]
Yeah Travis is back up at capacity. They were having issues the past few weeks

**Comment by jessesquires** [comment]
Nice! Now everything is actually green except that first build. Can we land? And follow up separately for 9.3?

**Comment by rnystrom** [comment]
@jessesquires do you want to disable 9.3 tests for the time being and get our green badge back?

**Comment by rnystrom** [comment]
Had an internal build issue, fixed tho. It's all green, landing.

**Comment by rnystrom** [comment]
Ok, pod lint is last thing. Putting up a new PR in a sec.

**Pull request closed without merging**
