### PR TITLE
Add equality guide

### LINKED ISSUE #253: Create new IGListDiffable + isEqual guide
Copy @rnystrom's internal post on *"IGListDiffable and good -isEqual: methods"* into a new guide.

https://fb.facebook.com/groups/505465172835436/permalink/1208294839219129/

### PR DESCRIPTION
**Pull request by rnystrom**
## Changes in this pull request

Fixes #253

### CODE REVIEW

**Comment by rnystrom** [comment]
@jessesquires do I just regen the docs to get this into the documentation page?

I think I should follow up w/ adding a small table-of-contents to the `README.md` too. Thoughts?

**Comment by jessesquires** [comment]
> do I just regen the docs to get this into the documentation page?

Yep! My flow is to make all changes and commit, then re-gen docs and commit only that. Like this:
https://github.com/Instagram/IGListKit/pull/258/commits

> I think I should follow up w/ adding a small table-of-contents to the README.md too. Thoughts?

Actually, I think we're good. These guides so up at the top of the side bar on the docs site:

screen shot 2016-11-24 at 2 33 29 pm

Maybe if people have trouble, we can call it out in the README later.

**Comment by jessesquires** [comment]
Oh -- and once you re-gen here, after we merge this it will all be live at https://instagram.github.io/IGListKit/

**Comment by rnystrom** [comment]
@jessesquires FYI i didn't gen the docs yet, will follow up

**Pull request closed without merging**
