### PR TITLE
Undefined symbols

### PR DESCRIPTION
**Pull request by RbBtSn0w**
## Changes in this pull request

Issue fixed: #

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [ ] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by lorixx** [comment]
Thanks Snow! It looks like CI still fails, do u mind look into it more?

**Comment by RbBtSn0w** [comment]
> Thanks Snow! It looks like CI still fails, do u mind look into it more?

can you help me, restart build?

**Comment by iperry90** [comment]
@RbBtSn0w it looks like there are some merge conflicts. Could you fix the conflicts and update the PR? Thanks!

**Comment by lorixx** [comment]
Could u rebase onto the latest master and run "./script/setup.sh" again? Then request merge again, thanks!

**Comment by RbBtSn0w** [comment]
yes. rebase and update it.

**Comment by RbBtSn0w** [comment]
> @RbBtSn0w it looks like there are some merge conflicts. Could you fix the conflicts and update the PR? Thanks!

it's fixed of the conflicts.

**Comment by joetam** [comment]
@RbBtSn0w if you're still looking to merge this, can you update with the CLA?

**Comment by RbBtSn0w** [comment]
> @RbBtSn0w if you're still looking to merge this, can you update with the CLA?

what's about CLA?

**Comment by TimOliver** [comment]
Hey folks! Sorry for not following up on this sooner. I recently did a pass on IGListKit's Xcode project to ensure all the source files were properly linked. This should be fine to close off now.

Thanks for the contribution, @RbBtSn0w!

**Pull request closed without merging**
