### PR TITLE
[#654] [#652] Added NS_UNAVAILABLE to new/init

### PR DESCRIPTION
**Pull request by Sherlouk**
Not sure what was expected for a "designated initialiser" feel free to school me and I'll do it!

(Also just had to google difference between + and - in ObjC)

Issue fixed: #654, #652

### CODE REVIEW

**Comment by jessesquires** [comment]
@Sherlouk - like this:

https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.h#L102-L104

**Comment by Sherlouk** [comment]
@jessesquires The proxy already has an init like that?

https://github.com/Instagram/IGListKit/pull/662/files#diff-de1e3d1878c2e29b5729badb5635fee8L34

[more than possible I'm being super simple right now]

**Comment by jessesquires** [comment]
it needs `NS_DESIGNATED_INITIALIZER` 😄

**Comment by Sherlouk** [comment]
Ahh well when you say it like that it's obvious 😅
Done!

**Comment by jessesquires** [comment]
haha thanks @Sherlouk ! 💯

**Comment by Sherlouk** [comment]
Definitely need to work on my ObjC knowledge... lil Swift peasant

**Comment by heshamsalman** [comment]
@Sherlouk @jessesquires heads up the `NS_DESIGNATED_INITIALIZER` causing build failures. 
I'm too schwifty to know the objective-c significance of it, but i can google around 👍

**Comment by jessesquires** [comment]
thanks @heshamsalman !

fixed in #667

**Pull request closed without merging**
