### PR TITLE
Update version number in docs

### PR DESCRIPTION
**Pull request by Sherlouk**
Part of #707 
#trivial

### CODE REVIEW

**Comment by BasThomas** [comment]
🤔, do you want to lock in clients to `3.0.0`? Specifying just `3.0` will make things like `pod update` allow upgrading to patch versions.

**Comment by jessesquires** [comment]
@BasThomas the `~>` should allow minor and patch version updates

**Comment by BasThomas** [comment]
As I [understand](http://stackoverflow.com/a/20213930) it, this will let you go up to `8.0.9`, but not higher.

**Comment by jessesquires** [comment]
@BasThomas 👍 i think that might be right. will update

**Pull request closed without merging**
