### PR TITLE
Fixup project file corruption

### PR DESCRIPTION
**Pull request by rnystrom**
Continuing issues raised in #1068. Project file was totally busted for macOS and AppleTV.

### CODE REVIEW

**Comment by rnystrom** [comment]
Likely Travis will still fail, but that's ok. Will merge in the morning and rebase #1068.

**Comment by jessesquires** [comment]
@rnystrom yep I made these changes in #1068

**Comment by rnystrom** [comment]
@jessesquires oh, ok. Do you want me to unland this? Or we can recreate #1068 on top? Are AppleTV tests failing the only issue now?

**Comment by jessesquires** [comment]
I fixed the conflicts in #1068 😬 

See all my other comments there for updates.

**Pull request closed without merging**
