### PR TITLE
Delete duplicate headers in `IGListKit.h`

### PR DESCRIPTION
**Pull request by hanton**
## Changes in this pull request

Delete duplicate headers in `IGListKit.h`

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by hanton** [comment]
hi, CI fails with an error, which is unrelated to the PR, could anyone have a check? Thanks :)

```
$ bundle exec pod lib lint
 -> IGListKit (3.4.0)
    - WARN  | url: The URL (https://twitter.com/fbOpenSource) is not reachable.
    - NOTE  | [IGListKit/Diffing,IGListKit/Default] xcodebuild:  note: Using new build system
    - NOTE  | [IGListKit/Diffing,IGListKit/Default] xcodebuild:  note: Planning build
    - NOTE  | [IGListKit/Diffing,IGListKit/Default] xcodebuild:  note: Constructing build description
    - NOTE  | [IGListKit/Diffing,IGListKit/Default] xcodebuild:  warning: Capabilities for App may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'App')
[!] IGListKit did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it).
You can use the `--no-clean` option to inspect any issue.
The command "bundle exec pod lib lint" exited with 1.
```

**Comment by bdotdub** [comment]
Hi @hanton – thanks for these contribs! I'll take a look at these today :)

**Comment by bdotdub** [comment]
Hi @hanton – this looks good to me! Can you rebase on top of master so that the build can run with the fix?

**Comment by hanton** [comment]
> Hi @hanton – this looks good to me! Can you rebase on top of master so that the build can run with the fix?

Done :)

**Pull request closed without merging**
