### PR TITLE
Makes SelectionModel struct, not class.

### PR DESCRIPTION
**Pull request by valeriyvan**
## Changes in this pull request

Makes SelectionModel struct, not class.

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [ ] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/CONTRIBUTING.md)

It has obvious value semantic.

### CODE REVIEW

**Comment by rnystrom** [comment]
Does this actually work tho? `IGListDiffable` is an Objective-C protocol which requires a class, not struct. I have a feeling that force-unwrap will crash.

**Comment by valeriyvan** [comment]
Doesn't matter if it works. Looks great!

**Comment by valeriyvan** [comment]
Clone, build, run and give it a try!

**Comment by rnystrom** [comment]
Lol mother of god why does this work?!? @jessesquires help

If I break in [`-[IGListAdapter updateObjects:]`](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L388) and print `objects`, I get:

```
(lldb) po objects
<_TtGCs23_ContiguousArrayStoragePSo14IGListDiffable__ 0x610000260d40>(
IGListKitExamples.SelectionModel(options: ["Leverage agile", "frameworks", "robust synopsis", "high level", "overviews", "Iterative approaches", "corporate strategy", "foster collaborative", "overall value", "proposition", "Organically grow", "holistic world view", "disruptive", "innovation", "workplace diversity", "empowerment"], type: IGListKitExamples.SelectionModelType.none),
IGListKitExamples.SelectionModel(options: ["Bring to the table", "win-win", "survival", "strategies", "proactive domination", "At the end of the day", "going forward", "a new normal", "evolved", "generation X", "runway heading", "streamlined", "cloud solution", "User generated", "content", "in real-time", "multiple touchpoints", "offshoring"], type: IGListKitExamples.SelectionModelType.nib),
IGListKitExamples.SelectionModel(options: ["Aenean lacinia bibendum nulla sed consectetur. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum.", "Donec sed odio dui. Donec id elit non mi porta gravida at eget metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed posuere consectetur est at lobortis. Cras justo odio, dapibus ac facilisis in, egestas eget quam.", "Sed posuere consectetur est at lobortis. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum."], type: IGListKitExamples.SelectionModelType.fullWidth)
)
```

Soooooo you can convert a Swift `struct` to an `NSObject` by force unwrapping? Next up we should figure out if the `IGListDiffable` methods can be used (`diffIdentifier` and `isEqualToDiffableObject`).

**Comment by valeriyvan** [comment]
I would like to know magic behind this!

**Comment by jessesquires** [comment]
lol

1. My guess is that this is a bug in Swift 3, from all of the bridging changes.
2. We should not merge this until we understand what's happening.

**Comment by zhubofei** [comment]
`struct` in Swift can conform to protocol though.

**Comment by rnystrom** [comment]
@zhubofei sure structs can conform to _Swift_ protocols, but not Objective-C ones.

Credit to @swolchok for finding out why this works. Our default `NSObject+IGListDiffable` category auto conforms to `IGListDiffable`. Swift is boxing these structs with an `NSObject` subclass:

https://github.com/apple/swift/blob/c3b7709a7c4789f1ad7249d357f69509fb8be731/stdlib/public/runtime/SwiftValue.h

So the default category is executing _on the box_, not on the objects themselves.

I'm going to close this out b/c definitely not intended behavior! Don't want to give the wrong example here.

**Comment by jessesquires** [comment]
Ahhhh 💡 

This is because of `NSArray`, I think.

As in, to bridge a Swift `Array` of value types (`struct`s) into Objective-C you *have to* bridge to `NSArray` and thus box all of the elements.

@rnystrom -- We should open a bug at http://bugs.swift.org

**Comment by jessesquires** [comment]
Doug Gregor confirmed boxing behavior:

https://twitter.com/dgregor79/status/798738755322396672

**Pull request closed without merging**
